### ISSUE TITLE
Failed getting results from TehConnection

### ISSUE THREAD

**Issue by mescon** [flightlevel/TehConnectionCouchPotatoPlugin#4]
### Steps to reproduce:
1. .. Automated search from CP
2. .. 

### Information:
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 69825f9d (2015-05-27 14:06:41)
Running on: Windows 8.1

### Logs:
```
07-28 14:16:10 ERROR [            tehconnection] Failed getting results from TehConnection: Traceback (most recent call last):
  File "C:\Users\mescon\AppData\Roaming\CouchPotato\custom_plugins\tehconnection\main.py", line 101, in _searchOnTitle
    torrentdata.torrentname = (namedata.text.splitlines()[1]).strip()
AttributeError: 'NoneType' object has no attribute 'text' 
```

**Comment by flightlevel** [comment]
@mescon Is this still occurring for you?

I can't reproduce. Wondering if it was just a temporary tehconnection server/connectivity issue?

**Comment by mescon** [comment]
@flightlevel Yep. The provider functions as should be, but I still get these for every search:

```
08-02 16:47:06 ERROR [            tehconnection] Unable to convert datetime from TehConnection: Traceback (most recent call last):
  File "C:\Users\mescon\AppData\Roaming\CouchPotato\custom_plugins\tehconnection\main.py", line 136, in _searchOnTitle
    addeddatetuple = time.strptime(dateaddedstr, '%b %d %Y, %H:%M')
  File "C:\Python27\lib\_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "C:\Python27\lib\_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data u'Oct 08 2009, 18:07' does not match format '%b %d %Y, %H:%M' 
```

**Comment by flightlevel** [comment]
@mescon I don't think its the date format because you can see what tehconnection is spitting out in your error `'Oct 08 2009, 18:07'`
I tried both your examples on my computer and they worked fine. Google found a couple reports of the same thing, maybe a combo of OS and python version, I have no idea.

You can try creating a simple python file below and see what happens out of interest.

`import time`
`addeddatetuple = time.strptime(u'Oct 17 2013, 19:35', '%b %d %Y, %H:%M')`
`torrentdata = int(time.mktime(addeddatetuple))`
`print(torrentdata)`

Anyway its not critical, the couchpotato standard providers don't provide a release age anyway.
To stop the errors go to your custom_plugin folder, edit the main.py file in the tehconnection folder and put a # in front of the word log
from `log.error('Unable to convert datetime from %s: %s', (self.getName(), traceback.format_exc()))`
to this `#log.error('Unable to convert datetime from %s: %s', (self.getName(), traceback.format_exc()))`
Then delete the main.pyc and restart CP.

**Comment by flightlevel** [comment]
You could try below as well and see what happens, maybe datetime instead time?

`import datetime`
`addeddatetime = datetime.datetime.strptime(u'Oct 17 2013, 19:35', '%b %d %Y, %H:%M')`
`ddd = int((addeddatetime - datetime.datetime(1970, 1, 1)).total_seconds())`
`print(str(ddd))`

**Comment by mescon** [comment]
I'll try that tonight and report back!
